#ifndef _FE_CORE_RUNTIME_EXCEPTION_MODE_H_
#define _FE_CORE_RUNTIME_EXCEPTION_MODE_H_
// Copyright © from 2023 to current, UNKNOWN STRYKER. All Rights Reserved.
#include "types.h"


BEGIN_NAMESPACE(FE)


enum struct EXCEPTION_MODE : uint8
{
    _LOG_EXCEPTION_HISTORY_ = 0,
    _ABORT_IMMEDIATELY_ = 1,
    _EXIT_WITH_CODE_ = 2
};


_MAYBE_UNUSED_ inline constexpr EXCEPTION_MODE _EXIT_WITH_CODE_ = EXCEPTION_MODE::_EXIT_WITH_CODE_;
_MAYBE_UNUSED_ inline constexpr EXCEPTION_MODE _LOG_EXCEPTION_HISTORY_ = EXCEPTION_MODE::_LOG_EXCEPTION_HISTORY_;
_MAYBE_UNUSED_ inline constexpr EXCEPTION_MODE _ABORT_IMMEDIATELY_ = EXCEPTION_MODE::_ABORT_IMMEDIATELY_;


END_NAMESPACE
#endif