name: Frogman-Engine-CI.yml

on:
  push:
    branches:
      - main
      - in-dev
      - chaos

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      
    steps:
    - uses: actions/checkout@v4

    - name: Build and Run Google Benchmark and Unit Tests
      run: |
        cd SDK/Core/Tests/Unit-Tests
        chmod +x build.sh
        chmod +x run-tests.sh
        ./build.sh
        ./run-tests.sh

    - name: LLVM libfuzzer Tests
      run: |
        cd SDK/Core/Tests/Fuzz-Tests
        chmod +x build-fuzz.sh
        chmod +x run-fuzz.sh
        ./build-fuzz.sh Debug
        ./run-fuzz.sh

        ./build-fuzz.sh RelWithDebInfo
        ./run-fuzz.sh

        ./build-fuzz.sh Release
        ./run-fuzz.sh
